### ISSUE TITLE
browser doesn't start

### ISSUE THREAD

**Issue by MrScrudg** [CvvT/crawler_sqlmap#1]
hello, while trying to run crawler_sqlmap i get such error:

[16:46:54] [DEBUG] Using adapter 'wsgiref' to run bottle
DEBUG:crawler.proxy.proxy:proxy error:
DEBUG:crawler.proxy.proxy:<HTTPFlow
  request = Request(CONNECT location.services.mozilla.com:443)
  error = Cannot establish TLS with client (sni: location.services.mozilla.com): TlsException("[('SSL routines', 'SSL3_READ_BYTES', 'tlsv1 alert unknown ca')]",)
  client_conn = <ClientConnection: [ssl] 127.0.0.1:38818>
  server_conn = <ServerConnection: [ssl: location.services.mozilla.com] location.services.mozilla.com:443>>
DEBUG:crawler.util.scheduler:options: {'url': 'http://testphp.vulnweb.com', 'batch': True, 'level': 1, 'threads': 1, 'timeout': 30}
DEBUG:crawler.browser.headlessBrowser:[*]Processing http://testphp.vulnweb.com
DEBUG:crawler.crawler:find one form http://testphp.vulnweb.com/search.php?test=query
DEBUG:crawler.util.scheduler:Empty queue, ready to quit
DEBUG:crawler.util.scheduler:start to exit, remaining tasks 0
DEBUG:autosql:0 tasks remained
DEBUG:crawler.util.urleliminate:http://demo.aisec.cn/demo/aisec/
DEBUG:crawler.browser.headlessBrowser:start to quit browser
DEBUG:crawler.proxy.proxy:proxy error:
DEBUG:crawler.proxy.proxy:<HTTPFlow
  request = Request(CONNECT tiles-cloudfront.cdn.mozilla.net:443)
  error = Cannot establish TLS with client (sni: tiles-cloudfront.cdn.mozilla.net): TlsException("[('SSL routines', 'SSL3_READ_BYTES', 'tlsv1 alert unknown ca')]",)
  client_conn = <ClientConnection: [ssl] 127.0.0.1:38831>
  server_conn = <ServerConnection: [ssl: tiles-cloudfront.cdn.mozilla.net] tiles-cloudfront.cdn.mozilla.net:443>>

can you please help me fix it ?

**Comment by MrScrudg** [comment]
+ if i don't set url to scan in crawler-sqlmap.py on 93 line and run as * -u "<set in the file url>" - crawler doesn't start at all

**Comment by MrScrudg** [comment]
browser starts, but the problem is with checksamehost plugin, can you check it please?

**Comment by CvvT** [comment]
The problem mentioned in the first comment might result from the Geckodriver you're using. Using the latest version of it will lead to the same error (if I remember correctly). Thus, I highly recommend you to use the version of v0.14.0. And, I'm not sure why you leave URL blank? You must set one URL as an entry to start the crawler.

**Comment by MrScrudg** [comment]
i used =14 version, url was set too - such errors still happen

**Comment by MrScrudg** [comment]
problem is with checksamehost module, while running with --test switch output says that crawler skips target host's urls

**Comment by CvvT** [comment]
My fault. I just fixed some bugs the other day. Please pull and use the latest code.
