### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by MrScrudg** [CvvT/crawler_sqlmap#3]
hello, got ssl error: 
[09:40:50] [DEBUG] Using adapter 'wsgiref' to run bottle
DEBUG:crawler.proxy.proxy:proxy error:
DEBUG:crawler.proxy.proxy:<HTTPFlow
  request = Request(CONNECT location.services.mozilla.com:443)
  error = Cannot establish TLS with client (sni: location.services.mozilla.com): TlsException("[('SSL routines', 'SSL3_READ_BYTES', 'tlsv1 alert unknown ca')]",)
  client_conn = <ClientConnection: [ssl] 127.0.0.1:37220>
  server_conn = <ServerConnection: [ssl: location.services.mozilla.com] location.services.mozilla.com:443>>

using last mitmproxy, python3.6

**Comment by CvvT** [comment]
Maybe the same reason with issue #1 . Try to use lower version of geckodriver (recommend v0.14.0). Let me know if you have any further question.

**Comment by CvvT** [comment]
Also, test with the latest firefox, which could also be the reason for SSL failure.

**Comment by MrScrudg** [comment]
used exactly 14 version and latest firefox
