### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cheban96** [CvvT/crawler_sqlmap#4]
![crawler_sqlmap](https://user-images.githubusercontent.com/11075696/43574398-c2ac32aa-964c-11e8-922b-f46af6a4a31f.png)
If exist Dockerfile, do you can his  my give.

**Comment by CvvT** [comment]
Sorry, I don't have the dockerfile. The error is resulted from mitmproxy. Check this: [issue](https://github.com/mitmproxy/mitmproxy/issues/3153).
